yarnPath: .yarn/releases/yarn-3.0.2.cjs

nodeLinker: node-modules

packageExtensions:
  strapi-plugin-users-permissions@*:
    dependencies:
      styled-components: "^5.3.1"
      koa: "^2.13.1"
      react-is: "^17.0.2"
      redux: "^4.1.1"
  strapi-plugin-upload@*:
    dependencies:
      styled-components: "^5.3.1"
      redux: "^4.1.1"
      react-is: "^17.0.2"
  strapi-plugin-graphql@*:
    dependencies:
      koa: "^2.13.1"
  strapi-plugin-content-type-builder@*:
    dependencies:
      styled-components: "^5.3.1"
      react-is: "^17.0.2"
  strapi-plugin-content-manager@*:
    dependencies:
      styled-components: "^5.3.1"
      react-is: "^17.0.2"
  strapi-helper-plugin@*:
    dependencies:
      jquery: "^3.6.0"
      popper.js: "^1.16.1"
      react-is: "^17.0.2"
  strapi-admin@*:
    dependencies:
      jquery: "^3.6.0"
      popper.js: "^1.16.1"
  "@buffetjs/styles@*":
    dependencies:
      react-dom: "^16"
      moment: "^2.29.1"
      "@babel/runtime": "^7.15.4"
  "@buffetjs/custom@*":
    dependencies:
      react-dom: "^16"
  "@buffetjs/core@*":
    dependencies:
      "@babel/runtime": "^7.15.4"
